
CCOPTS = -mf -5s -zp4 -bt=dos -IC:\WATCOM\H -IC:\GLIDE243\Src\Sst1\include

GLOBOBJS = &
 SOUND.OBJ &
 KEYBOARD.OBJ &
 CAMERA.OBJ &
 OBJECT.OBJ &
 MESH.OBJ &
 TIMER.OBJ &
 FILE.OBJ &
 TEXTURE.OBJ &
 TEXT.OBJ &
 PRIMITIV.OBJ &
 MATRIX.OBJ &
 FASTMATH.OBJ &
 MAIN.OBJ

all: MAIN.EXE

MAIN.EXE: $(GLOBOBJS)
	wlink @MAIN.LNK

.c.obj:
	wcc386 $(CCOPTS) -fo=$[*.obj $[*.c

clean: .SYMBOLIC
	DEL SOUND.OBJ
	DEL SOUND.ERR
	DEL KEYBOARD.OBJ
	DEL KEYBOARD.ERR
	DEL CAMERA.OBJ
	DEL CAMERA.ERR
 	DEL OBJECT.OBJ
	DEL OBJECT.ERR
 	DEL MESH.OBJ
	DEL MESH.ERR
 	DEL TIMER.OBJ
	DEL TIMER.ERR
 	DEL FILE.OBJ
	DEL FILE.ERR
 	DEL TEXTURE.OBJ
	DEL TEXTURE.ERR
 	DEL TEXT.OBJ
	DEL TEXT.ERR
 	DEL PRIMITIV.OBJ
	DEL PRIMITIV.ERR
 	DEL MATRIX.OBJ
	DEL MATRIX.ERR
 	DEL FASTMATH.OBJ
	DEL FASTMATH.ERR
 	DEL MAIN.OBJ
	DEL MAIN.ERR
	DEL MAIN.MAP
	DEL MAIN.EXE
